### ISSUE TITLE
Unexpected 'DEFAULT' (T_DEFAULT)

### ISSUE THREAD

**Issue by pankajmanay** [ncjoes/poppler-php#3]
When trying to run on the browser, following error is coming

FatalErrorException in /var/www/html/proj10/vendor/ncjoes/poppler-php/src/PopplerPhp/PopplerUtil.php line 349: syntax error, unexpected 'DEFAULT' (T_DEFAULT)

I am using following code to set the directory. Is this the correct way? There was no poppler folder in "vendor/bin" directory. So i created it.

// set Poppler utils binary location

        Config::setBinDirectory('/var/www/html/proj10/vendor/bin/poppler');

// set output directory
Config::setOutputDirectory('/var/www/html/proj10/storage/poppler-output');

**Comment by pankajmanay** [comment]
In changed "DEFAULT" to "DEFAULT_Something", error goes off. But when i run the code, its not converting to SVG. Also these below function are giving blank array

$info = $pdf->getInfo(); //returns an associative array
$authors = $pdf->getAuthors();

**Comment by ncjoes** [comment]
You can get an empty array if the PDF document's author tag is empty.
